"""Weekly digest output.

A plain-Markdown log that rides along on the `state` branch next to the
encrypted DB, grouped by ISO week. The DB is the source of truth; this file is
the human-readable view you can skim on a Monday.
"""
from __future__ import annotations

import datetime as dt
import logging
from dataclasses import dataclass
from pathlib import Path

from .config import now_ct

LOGGER = logging.getLogger("yt.digest")

HEADER = "# Weekly Digest — YouTube Comment Replies\n"


@dataclass
class DigestEntry:
    channel_name: str
    video_id: str
    video_title: str
    author_name: str
    comment_text: str
    reply_text: str


def _week_heading(when=None) -> str:
    when = when or now_ct()
    iso_year, iso_week, _ = when.isocalendar()
    monday = when - dt.timedelta(days=when.isoweekday() - 1)
    return f"## Week of {monday:%Y-%m-%d} ({iso_year}-W{iso_week:02d})"


def _one_line(text: str, limit: int = 160) -> str:
    """Collapse a comment to a single table-safe line."""
    flat = " ".join(text.split())
    if len(flat) > limit:
        flat = flat[: limit - 1].rstrip() + "…"
    return flat.replace("|", "\\|")


def append(
    path: Path | str,
    entries: list[DigestEntry],
    stats: dict,
) -> None:
    """Append this run's replies (and a one-line run summary) to the digest."""
    digest_path = Path(path)
    digest_path.parent.mkdir(parents=True, exist_ok=True)

    existing = digest_path.read_text() if digest_path.exists() else ""
    out: list[str] = []

    if not existing:
        out.append(HEADER)
        out.append(
            "\nOne entry per posted reply, newest run appended at the bottom. "
            "Generated by `.github/workflows/yt-comments.yml`.\n"
        )

    heading = _week_heading()
    if heading not in existing and heading not in "".join(out):
        out.append(f"\n{heading}\n")

    stamp = now_ct().strftime("%Y-%m-%d %H:%M CT")

    for entry in entries:
        video = entry.video_title or entry.video_id or "channel comment"
        out.append(
            f"\n- **{stamp}** · {entry.channel_name} · _{_one_line(video, 80)}_\n"
            f"  - **{entry.author_name or 'viewer'}:** {_one_line(entry.comment_text)}\n"
            f"  - **reply:** {_one_line(entry.reply_text, 300)}\n"
        )

    out.append(
        f"\n<sub>run {stamp} — scanned {stats.get('scanned', 0)}, "
        f"eligible {stats.get('eligible', 0)}, replied {stats.get('replied', 0)}, "
        f"skipped {stats.get('skipped', 0)}, failed {stats.get('failed', 0)}, "
        f"quota {stats.get('quota_used', 0)}u"
        f"{' (DRY RUN)' if stats.get('dry_run') else ''}</sub>\n"
    )

    with digest_path.open("a", encoding="utf-8") as handle:
        handle.write("".join(out))

    LOGGER.info("Digest updated: %s (+%d entries)", digest_path, len(entries))
